services:
  - type: web
    name: smart-portfolio-site
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn smart_portfolio_site.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: CLOUDINARY_CLOUD_NAME
        fromSecret: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        fromSecret: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        fromSecret: CLOUDINARY_API_SECRET
      - key: ALLOWED_HOSTS
        value: smart-portfolio-ogp7.onrender.com
