services:
  - type: web
    name: smart-portfolio-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn smart_portfolio_site.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: -fU_qN7LevuYVUAs6-psstfhT9jIxoHw5Kf-UTqwlx9tfWkfEOGtRjX3p7VcsswYE_dAA
      - key: ALLOWED_HOSTS
        value: Smart-Portfolio.onrender.com,localhost,127.0.0.1
