services:
  - type: web
    name: smart-portfolio-site
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn smart_portfolio_site.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: -fU_qN7LevuYVUAs6-psstfhT9jIxoHw5Kf-UTqwlx9tfWkfEOGtRjX3p7VcsswYE_dAA
      - key: ALLOWED_HOSTS
        value: smart-portfolio-ogp7.onrender.com,localhost,127.0.0.1
      - key: CLOUDINARY_CLOUD_NAME
        value: dnglmw8l0
      - key: CLOUDINARY_API_KEY
        value: 986362225853921
      - key: CLOUDINARY_API_SECRET
        value: nZREC-59laRxF120SXrm91XIUmE
